-- 1. 기존 테이블 및 객체 삭제 (초기화)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.app_event_logs;
DROP TABLE IF EXISTS public.profiles;
DROP TABLE IF EXISTS public.bingo_boards;

-- 2. 유저 프로필 테이블 생성 (Auth 연동)
CREATE TABLE public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  nickname text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
COMMENT ON TABLE public.profiles IS '사용자 프로필 정보 (Auth 동기화)';

-- 3. 빙고 보드 테이블 생성 (확장됨)
CREATE TABLE public.bingo_boards (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  
  -- 기간 및 그리드 설정
  period_type text default 'monthly' not null,
  period_value text not null, 
  grid_size text default '3x3' not null,
  
  -- 데이터 저장
  grid_data jsonb, 
  drawing_data jsonb, 
  
  -- 메타 데이터
  title text default '나의 빙고',
  
  -- [NEW] 분석용 요약 컬럼 (share_count 제거됨)
  visit_count integer default 1 not null,
  final_filled_count integer default 0 not null,
  is_decorated boolean default false not null,
  download_count integer default 0 not null,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- 중복 방지 (유저 + 기간 + 사이즈)
  CONSTRAINT unique_user_period_grid UNIQUE (user_id, period_type, period_value, grid_size)
);

COMMENT ON COLUMN public.bingo_boards.grid_data IS '빙고 셀 내용 (JSON)';
COMMENT ON COLUMN public.bingo_boards.drawing_data IS '그리기 패스 데이터 (JSON)';
COMMENT ON COLUMN public.bingo_boards.visit_count IS '페이지 방문 횟수';
COMMENT ON COLUMN public.bingo_boards.final_filled_count IS '빙고 완료된 셀 개수 (분석용)';
COMMENT ON COLUMN public.bingo_boards.is_decorated IS '꾸미기 기능 사용 여부';
COMMENT ON COLUMN public.bingo_boards.download_count IS '이미지 다운로드 횟수';

-- 4. 로그 데이터 테이블 생성
CREATE TABLE public.app_event_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  event_params jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
COMMENT ON TABLE public.app_event_logs IS '사용자 행동 로그 (클릭, 인터랙션 등)';
COMMENT ON COLUMN public.app_event_logs.event_params IS '이벤트 상세 속성 (JSON)';

-- 5. 보안 정책 (RLS) 설정

-- A. Profiles RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "본인 프로필 조회" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "본인 프로필 수정" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- B. Bingo Boards RLS
ALTER TABLE public.bingo_boards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "내 빙고 조회" ON public.bingo_boards FOR SELECT USING ( auth.uid() = user_id );
CREATE POLICY "내 빙고 생성" ON public.bingo_boards FOR INSERT WITH CHECK ( auth.uid() = user_id );
CREATE POLICY "내 빙고 수정" ON public.bingo_boards FOR UPDATE USING ( auth.uid() = user_id );
CREATE POLICY "내 빙고 삭제" ON public.bingo_boards FOR DELETE USING ( auth.uid() = user_id );

-- C. App Event Logs RLS
-- C. App Event Logs RLS
ALTER TABLE public.app_event_logs ENABLE ROW LEVEL SECURITY;
-- [변경] 로그인 유저뿐만 아니라 익명 유저도 로그 적재 가능하도록 허용
CREATE POLICY "누구나 로그 적재 가능" ON public.app_event_logs FOR INSERT WITH CHECK (true);

-- 6. 인덱스 및 트리거 설정

-- 인덱스
CREATE INDEX idx_bingo_user_period_grid ON public.bingo_boards (user_id, period_type, period_value, grid_size);

-- 트리거 함수: Bingo Boards Updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  new.updated_at = now();
  RETURN new;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER handle_updated_at
BEFORE UPDATE ON public.bingo_boards
FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 트리거 함수: Auth User 생성 시 Profile 자동 생성
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, nickname)
  VALUES (
    new.id,
    new.email,
    COALESCE(
      new.raw_user_meta_data->>'name',
      new.raw_user_meta_data->>'full_name',
      split_part(new.email, '@', 1)
    )
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Auth 트리거 등록
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 7. 카운트 증가용 RPC 함수 (Only Update)
CREATE OR REPLACE FUNCTION public.increment_bingo_count(
  p_user_id uuid,
  p_period_value text,
  p_grid_size text,
  p_column_name text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- 유효한 컬럼명인지 화이트리스트 검사 (share_count 제거됨)
  IF p_column_name NOT IN ('visit_count', 'download_count') THEN
    RAISE EXCEPTION 'Invalid column name: %', p_column_name;
  END IF;

  -- 오직 존재하는 행에 대해서만 업데이트 (중복 생성 방지)
  EXECUTE format('
    UPDATE public.bingo_boards
    SET %I = %I + 1
    WHERE user_id = $1
      AND period_value = $2
      AND grid_size = $3
  ', p_column_name, p_column_name)
  USING p_user_id, p_period_value, p_grid_size;
END;
$$;